$files = Get-ChildItem -Path "app/src/main/java/com/mamunwrites/todo" -Filter "*.java" -Recurse

foreach ($file in $files) {
    $content = Get-Content -Path $file.FullName -Raw
    
    # Fix imports first
    $content = $content -replace "import com\.google\.android\.material\.snackbaR;", "import com.google.android.material.snackbar.Snackbar;"
    $content = $content -replace "import com\.google\.android\.material\.appbaR;", "import com.google.android.material.appbar.MaterialToolbar;"
    
    # Fix classes and interfaces
    $content = $content -replace "implements TaskAdapteR", "implements TaskAdapter.OnTaskContextMenuListener"
    $content = $content -replace "extends RecyclerView\.Adapter<TaskAdapteR>", "extends RecyclerView.Adapter<TaskAdapter.TaskViewHolder>"
    $content = $content -replace "extends RecyclerView\.Adapter<NotificationTaskAdapteR>", "extends RecyclerView.Adapter<NotificationTaskAdapter.TaskViewHolder>"
    
    # Fix method calls - replace all R-suffix issues with correct method names
    $content = $content -replace "supeR\(", "super("
    $content = $content -replace "adapteR\(", "adapter.set"
    $content = $content -replace "toolbaR\(", "toolbar.setNavigationOnClickListener("
    $content = $content -replace "categorySpinneR\(", "categorySpinner.setAdapter("
    $content = $content -replace "prioritySpinneR\(", "prioritySpinner.setAdapter("
    $content = $content -replace "buildeR\(", "builder.set"
    $content = $content -replace "CalendaR\(\)", "Calendar.getInstance()"
    $content = $content -replace "calendaR\(CalendaR", "calendar.get(Calendar"
    $content = $content -replace "CalendaR_OF_MONTH", "Calendar.DAY_OF_MONTH"
    $content = $content -replace "CalendaR", "Calendar"
    $content = $content -replace "PackageManageR_GRANTED", "PackageManager.PERMISSION_GRANTED"
    $content = $content -replace "IntegeR", "Integer"
    $content = $content -replace "viewHoldeR\(\)", "viewHolder.getAdapterPosition()"
    $content = $content -replace "ItemTouchHelpeR", "ItemTouchHelper"
    $content = $content -replace "SnackbaR", "Snackbar"
    $content = $content -replace "filteR", "filter.equals"
    
    # Fix resource references
    $content = $content -replace "R\.menu_multi_select", "R.menu.menu_multi_select"
    $content = $content -replace "R\.action_delete_selected", "R.id.action_delete_selected"
    $content = $content -replace "R\.action_mark_done", "R.id.action_mark_done"
    $content = $content -replace "R\.activity_main", "R.layout.activity_main"
    $content = $content -replace "R\.activity_developer_info", "R.layout.activity_developer_info"
    $content = $content -replace "R\.activity_privacy_policy", "R.layout.activity_privacy_policy"
    $content = $content -replace "R\.toolbar", "R.id.toolbar"
    $content = $content -replace "R\.notificationIcon", "R.id.notificationIcon"
    $content = $content -replace "R\.recyclerView", "R.id.recyclerView"
    $content = $content -replace "R\.fabAdd", "R.id.fabAdd"
    $content = $content -replace "R\.emptyState", "R.id.emptyState"
    $content = $content -replace "R\.searchInput", "R.id.searchInput"
    $content = $content -replace "R\.tabLayout", "R.id.tabLayout"
    $content = $content -replace "R\.ExamDialog", "R.style.ExamDialog"
    $content = $content -replace "R\.dialog_add_task", "R.string.dialog_add_task"
    $content = $content -replace "R\.dialog_edit_task", "R.string.dialog_edit_task"
    $content = $content -replace "R\.dialog_add_edit_task", "R.layout.dialog_add_edit_task"
    $content = $content -replace "R\.editTaskText", "R.id.editTaskText"
    $content = $content -replace "R\.dueDateView", "R.id.dueDateView"
    $content = $content -replace "R\.categorySpinner", "R.id.categorySpinner"
    $content = $content -replace "R\.prioritySpinner", "R.id.prioritySpinner"
    $content = $content -replace "R\.spinner_item", "R.layout.spinner_item"
    $content = $content -replace "R\.spinner_dropdown_item", "R.layout.spinner_dropdown_item"
    $content = $content -replace "R\.dialog_add", "R.string.dialog_add"
    $content = $content -replace "R\.dialog_save", "R.string.dialog_save"
    $content = $content -replace "R\.dialog_cancel", "R.string.dialog_cancel"
    $content = $content -replace "R\.developer_info", "R.string.developer_info"
    $content = $content -replace "R\.developer_info_text", "R.string.developer_info_text"
    $content = $content -replace "R\.developerInfoText", "R.id.developerInfoText"
    $content = $content -replace "R\.privacyPolicyText", "R.id.privacyPolicyText"
    $content = $content -replace "R\.privacy_policy", "R.string.privacy_policy"
    $content = $content -replace "R\.privacy_policy_text", "R.string.privacy_policy_text"
    $content = $content -replace "R\.category_work", "R.string.category_work"
    $content = $content -replace "R\.category_personal", "R.string.category_personal"
    $content = $content -replace "R\.category_urgent", "R.string.category_urgent"
    $content = $content -replace "R\.category_shopping", "R.string.category_shopping"
    $content = $content -replace "R\.category_other", "R.string.category_other"
    $content = $content -replace "R\.priority_high", "R.string.priority_high"
    $content = $content -replace "R\.priority_medium", "R.string.priority_medium"
    $content = $content -replace "R\.priority_low", "R.string.priority_low"
    $content = $content -replace "R\.filter_all", "R.string.filter_all"
    $content = $content -replace "R\.filter_done", "R.string.filter_done"
    $content = $content -replace "R\.filter_active", "R.string.filter_active"
    $content = $content -replace "R\.emptyStateContainer", "R.id.emptyStateContainer"
    $content = $content -replace "R\.dialog_task_deleted", "R.string.dialog_task_deleted"
    $content = $content -replace "R\.dialog_undo", "R.string.dialog_undo"
    $content = $content -replace "R\.app_bar_menu", "R.menu.app_bar_menu"
    $content = $content -replace "R\.notification_dark", "R.drawable.notification_dark"
    $content = $content -replace "R\.notification", "R.drawable.notification"
    $content = $content -replace "R\.notification_empty", "R.string.notification_empty"
    $content = $content -replace "R\.floating_notification", "R.layout.floating_notification"
    $content = $content -replace "R\.notification_tasks_recycler", "R.id.notification_tasks_recycler"
    $content = $content -replace "R\.notification_dismiss_button", "R.id.notification_dismiss_button"
    $content = $content -replace "R\.checkbox", "R.id.checkbox"
    $content = $content -replace "R\.text", "R.id.text"
    $content = $content -replace "R\.dueDate", "R.id.dueDate"
    $content = $content -replace "R\.dateContainer", "R.id.dateContainer"
    $content = $content -replace "R\.category", "R.id.category"
    $content = $content -replace "R\.priority", "R.id.priority"
    $content = $content -replace "R\.notification_task_text", "R.id.notification_task_text"
    $content = $content -replace "R\.notification_task_date", "R.id.notification_task_date"
    $content = $content -replace "R\.priority_indicator", "R.id.priority_indicator"
    $content = $content -replace "R\.notification_task_item", "R.layout.notification_task_item"
    $content = $content -replace "R\.item_task", "R.layout.item_task"
    $content = $content -replace "R\.share_app", "R.string.share_app"
    $content = $content -replace "R\.action_privacy_policy", "R.id.action_privacy_policy"
    $content = $content -replace "R\.action_developer_info", "R.id.action_developer_info"
    $content = $content -replace "R\.action_share_app", "R.id.action_share_app"
    $content = $content -replace "R\.action_export", "R.id.action_export"
    $content = $content -replace "R\.action_import", "R.id.action_import"
    $content = $content -replace "R\.action_multiselect", "R.id.action_multiselect"
    $content = $content -replace "R\.action_change_language", "R.id.action_change_language"
    $content = $content -replace "R\.action_test_notification", "R.id.action_test_notification"
    
    # Fix color resources
    $content = $content -replace "R\.mamunwrites\.todo\.R\.selection_highlight", "R.color.selection_highlight"
    $content = $content -replace "R\.mamunwrites\.todo\.R\.overdue_background", "R.color.overdue_background"
    $content = $content -replace "R\.mamunwrites\.todo\.R\.overdue_text", "R.color.overdue_text"
    $content = $content -replace "R\.mamunwrites\.todo\.R\.date_background", "R.color.date_background"
    $content = $content -replace "R\.mamunwrites\.todo\.R\.date_text", "R.color.date_text"
    $content = $content -replace "R\.mamunwrites\.todo\.R\.priority_high", "R.color.priority_high"
    $content = $content -replace "R\.mamunwrites\.todo\.R\.priority_medium", "R.color.priority_medium"
    $content = $content -replace "R\.mamunwrites\.todo\.R\.priority_low", "R.color.priority_low"
    
    # Fix specific method references that are broken
    $content = $content -replace "adapteR\\.", "adapter."
    $content = $content -replace "holdeR\\.", "holder."
    $content = $content -replace "buildeR\\.set\\(getString", "builder.setPositiveButton(getString"
    $content = $content -replace "adapteR\\.set\\(this\\)", "adapter.setOnTaskContextMenuListener(this)"
    $content = $content -replace "adapteR\\.set\\(this::updateActionModeTitle\\)", "adapter.setOnSelectionChangedListener(this::updateActionModeTitle)"
    $content = $content -replace "categorySpinneR\\(\\)", "categorySpinner.getSelectedItem()"
    $content = $content -replace "prioritySpinneR\\(\\)", "prioritySpinner.getSelectedItem()"
    $content = $content -replace "alertDialog dialog = buildeR\\(\\);", "AlertDialog dialog = builder.create();"
    $content = $content -replace "buildeR\\.set\\(dialogView\\)", "builder.setView(dialogView)"
    $content = $content -replace "exportLauncheR\\(", "exportLauncher.launch("
    $content = $content -replace "importLauncheR\\(", "importLauncher.launch("
    $content = $content -replace "notificationManageR\\(", "notificationManager.createNotificationChannel("
    $content = $content -replace "notificationManageR\\(notificationId, buildeR\\(\\)\\)", "notificationManager.notify(notificationId, builder.build())"
    $content = $content -replace "FileProvideR\\(", "FileProvider.getUriForFile("
    $content = $content -replace "CharacteR\\(", "Character.isDigit("
    $content = $content -replace "ComparatoR\\(", "Comparator.comparing("
    $content = $content -replace "android\\.app\\.NotificationManageR", "android.app.NotificationManager.IMPORTANCE"
    $content = $content -replace "android\\.app\\.NotificationManageR\\)", "android.app.NotificationManager.class)"
    $content = $content -replace "holdeR\\.getContext\\(\\)", "holder.itemView.getContext()"
    $content = $content -replace "adapteR\\(newPosition\\)", "adapter.notifyItemChanged(newPosition)"
    $content = $content -replace "adapteR\\(position, newPosition\\)", "adapter.notifyItemMoved(position, newPosition)"
    $content = $content -replace "adapteR\\(\\)", "adapter.notifyDataSetChanged()"
    $content = $content -replace "emptyStateContaineR\\(", "emptyStateContainer.setVisibility("
    $content = $content -replace "adapteR\\.getSelectedTasks\\(\\).size\\(\\)", "adapter.getSelectedTasks().size()"
    $content = $content -replace "adapteR\\.getSelectedTasks\\(\\)", "adapter.getSelectedTasks()"
    $content = $content -replace "adapteR\\(true\\)", "adapter.setMultiSelectMode(true)"
    $content = $content -replace "adapteR\\(false\\)", "adapter.setMultiSelectMode(false)"
    $content = $content -replace "adapteR\\.getItemCount\\(\\)", "adapter.getItemCount()"
    $content = $content -replace "adapteR\\(i\\)", "adapter.notifyItemChanged(i)"
    $content = $content -replace "viewHoldeR\\(\\)", "viewHolder.getAdapterPosition()"
    $content = $content -replace "LayoutInflateR\\(", "LayoutInflater.from("
    $content = $content -replace "holdeR\\.setVisibility\\(", "holder.setVisibility("
    $content = $content -replace "holdeR\\.setChipBackgroundColorResource\\(", "holder.setChipBackgroundColorResource("
    $content = $content -replace "holdeR\\.setText\\(", "holder.setText("
    $content = $content -replace "selectionChangedListeneR\\(\\)", "selectionChangedListener.onSelectionChanged()"
    $content = $content -replace "onTaskClickListeneR\\(", "onTaskClickListener.onTaskClick("
    $content = $content -replace "contextMenuListeneR\\(", "contextMenuListener.onEditTask("
    $content = $content -replace "android.R.coloR", "android.R.color.white"

    # Ensure proper R import
    if (-not ($content -match "import com\.mamunwrites\.todo\.R;")) {
        $content = $content -replace "(package com\.mamunwrites\.todo;)", "`$1`n`nimport com.mamunwrites.todo.R;"
    }
    
    Set-Content -Path $file.FullName -Value $content
}

Write-Host "Fixed R references in all Java files" 